### ISSUE TITLE
Add visual indicator for islands, similar to loops

### ISSUE THREAD

**Issue by adamburgess** [gereleth/hexapipes#56]
Since islands are invalid, it would be useful to show something when an island is created.

Might be a good idea to filter out islands that are simply two dead ends connected, though...

**Comment by gereleth** [comment]
An island is basically a disconnected part. And unconnected parts will already have a different color, so they are easier to notice than loops. Unless their random colors turn out to be very similar. I notice this sometimes but not often.

I had some ideas about rerolling new color if it's too similar to a nearby color. But it turns out computing perceptual similarity between colors is a nontrivial task. So thisinitiative stalled).

**Comment by adamburgess** [comment]
Colours are useful for different parts, but there's a distinction that should be made when you have an part that has no unconnected ends -- this is what I meant by island.

Having an island is invalid, which helps you discount a rotation. e.g. a piece that has two rotations, but one creates an Island, means it has to be the other.

With increasingly large puzzles where you can't see the entire chain of pieces it would be useful to know if you've created an island or not

**Comment by gereleth** [comment]
Ok, I see what you mean. I don't feel much of a personal need for this feature but maybe it's because this isn't implemented and so I've learned to live without)).

This seems related to tracking disconnects or free ends in #52 . When a certain part has no more free ends we'd highlight it as an island. 

Both features require tracking some additional data about game state, like which connections are mutual or which tiles have free ends. I'm slowly thinking about ways to do this without introducing too much additional complexity into the already intricate game logic =).
