### ISSUE TITLE
Should rotation animations be faster?

### ISSUE THREAD

**Issue by gereleth** [gereleth/hexapipes#70]
A speedster player told me that the current 100ms animations feel too sluggish.

I'm considering adding a setting for animation speed. Maybe with 3 levels: usual (100 ms), fast (30? ms) and instant (0 ms).

You can try out different durations by inspecting a pipe and editing this circled value in the browser.

![image](https://user-images.githubusercontent.com/6080076/215556132-e254d2a8-6df8-4fb8-80a9-d3738a83d143.png)

Any thoughts on this? =)

**Comment by mtmail** [comment]
Thanks to the screenshot I was able to play around (pun intended) a bit with the values. Seem like a good idea.

(I'm not the speedster player)

**Comment by gereleth** [comment]
Square pipes puzzles on this site do feel more snappy indeed: https://www.puzzle-pipes.com/ 

As far as I can see they have transition set to `.1s ease`. So the equivalent for hexagonal pipes would be something like `66ms ease` (to account for 60 vs 90 degress turns). I tried it out and somehow things still feel slower than there)). Maybe this is just due to 150% more clicks when you have six directions instead of four and use click to rotate mode.

**Comment by Jaybrainer** [comment]
The difference in "speed" feel can also be contributed to when rotations are registered. Because drags are currently made with left-click, rotations must be registered with mouseup. On puzzle-pipes, rotations are registered on mousedown. Resolving this discrepancy would likely warrant a full rewrite/rework of the controls.
